apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: dynaclaimz

# Default profile - local development with Docker Compose
build:
  artifacts:
  - image: dynaclaimz/api-gateway
    context: services/api-gateway
    docker:
      dockerfile: Dockerfile
  - image: dynaclaimz/user-service
    context: services/user-service
    docker:
      dockerfile: Dockerfile
  - image: dynaclaimz/policy-service
    context: services/policy-service
    docker:
      dockerfile: Dockerfile
  - image: dynaclaimz/claims-service
    context: services/claims-service
    docker:
      dockerfile: Dockerfile
  - image: dynaclaimz/quotes-service
    context: services/quotes-service
    docker:
      dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true

deploy:
  docker:
    useCompose: true
    images:
    - dynaclaimz/api-gateway
    - dynaclaimz/user-service
    - dynaclaimz/policy-service
    - dynaclaimz/claims-service
    - dynaclaimz/quotes-service

portForward:
- resourceType: service
  resourceName: api-gateway
  port: 3000
  localPort: 3000

# Profiles for different environments
profiles:
# Local Kubernetes profile (e.g., minikube, Docker Desktop k8s)
- name: local-k8s
  build:
    artifacts:
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/api-gateway
      context: services/api-gateway
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/user-service
      context: services/user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "src/**/*.ts"
          dest: /app/src
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/policy-service
      context: services/policy-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "src/**/*.ts"
          dest: /app/src
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/claims-service
      context: services/claims-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "src/**/*.ts"
          dest: /app/src
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/quotes-service
      context: services/quotes-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "src/**/*.ts"
          dest: /app/src
    local:
      push: false
      useBuildkit: true
  
  manifests:
    rawYaml:
    - k8s/namespace.yaml
    - k8s/secrets.yaml
    - k8s/services/*.yaml
    - k8s/deployments/*.yaml
  
  portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: dynaclaimz
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: user-service
    namespace: dynaclaimz
    port: 3001
    localPort: 3001

# EKS Development profile
- name: eks-dev
  build:
    artifacts:
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/api-gateway
      context: services/api-gateway
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/user-service
      context: services/user-service
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/policy-service
      context: services/policy-service
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/claims-service
      context: services/claims-service
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/quotes-service
      context: services/quotes-service
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/locust
      context: load-tests
      docker:
        dockerfile: Dockerfile
    local:
      push: true
      useBuildkit: true
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha

  manifests:
    rawYaml:
    - k8s/namespace.yaml
    - k8s/secrets.yaml
    - k8s/services/*.yaml
    - k8s/deployments/*.yaml
    - k8s/jobs/database/db-init-job.yaml

  deploy:
    kubectl:
      hooks:
        before:
        - host:
            command:
            - sh
            - -c
            - |
              # Login to ECR
              aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 446130280781.dkr.ecr.us-east-1.amazonaws.com

  portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: dynaclaimz
    port: 80
    localPort: 3000

# EKS Development Iteration profile (for fast iteration without commits)
- name: eks-dev-iterate
  build:
    artifacts:
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/api-gateway
      context: services/api-gateway
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/user-service
      context: services/user-service
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/policy-service
      context: services/policy-service
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/claims-service
      context: services/claims-service
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/quotes-service
      context: services/quotes-service
      docker:
        dockerfile: Dockerfile
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/locust
      context: load-tests
      docker:
        dockerfile: Dockerfile
    
    tagPolicy:
      customTemplate:
        template: "latest"  # Always use :latest tag for fast iteration
    
    local:
      push: true  # Push to ECR
      useBuildkit: true
      concurrency: 3

  manifests:
    rawYaml:
    - k8s/namespace.yaml
    - k8s/secrets.yaml
    - k8s/services/*.yaml
    - k8s/deployments/*.yaml
    - k8s/jobs/database/db-init-job.yaml

  deploy:
    kubectl:
      hooks:
        before:
        - host:
            command:
            - sh
            - -c
            - |
              # Login to ECR
              aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 446130280781.dkr.ecr.us-east-1.amazonaws.com

  portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: dynaclaimz
    port: 80
    localPort: 3000

# EKS Production profile
- name: eks-prod
  build:
    artifacts:
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/api-gateway
      context: services/api-gateway
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: production
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/user-service
      context: services/user-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: production
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/policy-service
      context: services/policy-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: production
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/claims-service
      context: services/claims-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: production
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/quotes-service
      context: services/quotes-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: production
    - image: 446130280781.dkr.ecr.us-east-1.amazonaws.com/dynaclaimz/locust
      context: load-tests
      docker:
        dockerfile: Dockerfile
    local:
      push: true
      useBuildkit: true
    tagPolicy:
      gitCommit:
        variant: Tags

  manifests:
    rawYaml:
    - k8s/namespace.yaml
    - k8s/secrets.yaml
    - k8s/services/*.yaml
    - k8s/deployments/*.yaml
    - k8s/jobs/database/db-init-job.yaml

  deploy:
    kubectl:
      hooks:
        before:
        - host:
            command:
            - sh
            - -c
            - |
              # Login to ECR
              aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 446130280781.dkr.ecr.us-east-1.amazonaws.com
